### PR TITLE
S01E09: Testing RabbitMQ Resiliency with Chaos Mesh

### LINKED ISSUE #19: Testing RabbitMQ Resiliency
How does RabbitMQ handle network latency? What about a clean network partition? And a partial network partition, or [Byzantine fault](https://en.wikipedia.org/wiki/Byzantine_fault)?

We have at our disposal a wide variety of tooling for the Kubernetes infrastructure that will let us make new discoveries about the behaviour of RabbitMQ.

[Chaos Mesh](https://github.com/chaos-mesh/chaos-mesh) - Chaos testing framework for Kubernetes clusters by the CNCF, very recently made GA. Allows for many cluster disturbances to be run continuously, or on a cron schedule, and on subsets of pods. The different chaos events are known as experiments, which consist of:

- Pods / Containers going down or failing
- Network faults, such as partitions or packet loss/duplication/corruption etc.
- CPU / memory stress in Pods
- System Clock time offsets
- Filesystem faults, such as permissions failures or other IO operation errors/delays
- Injecting Kernel faults into pods

## Obligatory commit strip

[Strip-Ca-marche-plus-650-finalenglish](https://www.commitstrip.com/en/2014/07/03/then-all-of-a-sudden-everything-fails/?)

## Other tools

[RabbitTestTool](https://github.com/rabbitmq/RabbitTestTool) - Tool for orchestration and benchmarking of RabbitMQ clusters in EC2, GKE or EKS. Allows for 'playlists' to be created and run, where a playlist consists of systems, benchmarks and workloads. This allows easy A/B benchmarking of the same workloads against different systems, or different workloads on the same system.

[Kubestone](https://github.com/xridge/kubestone) - Benchmarking tool for Kubernetes clusters. Implements a number of controllers for various benchmarking tools, such as system performance profiling, HTTP load benchmarks, etc. Can be extended with custom operators to support different benchmarks. For example, we could contribute to this project to provide a RabbitMQ benchmark if we so wished.

[Sonobuoy](https://github.com/vmware-tanzu/sonobuoy) - Security benchmarking & e2e testing of K8s workloads. Extensible with custom plugins. We could also contribute to this project with a RabbitMQ benchmarking plugin.

### PR DESCRIPTION
**Pull request by gerhard**
# TGIR S01E09: Testing RabbitMQ Resiliency with Chaos Mesh

* Proposed via [rabbitmq/tgir#19](https://github.com/rabbitmq/tgir/issues/19)
* Hosted by [@corodotdev](https://twitter.com/corodotdev) & [@gerhardlazu](https://twitter.com/gerhardlazu)
* Published on: 2020-12-31
* Video: https://www.youtube.com/watch?v=y2HAJBiXsw0

[TGIR S01E09: Testing RabbitMQ Resiliency with Chaos Mesh](https://www.youtube.com/watch?v=y2HAJBiXsw0)

How does RabbitMQ handle network latency?

What about a clean network partition?

And a partial network partition, or [Byzantine failure](https://blog.cloudflare.com/a-byzantine-failure-in-the-real-world/)?

We have at our disposal a wide variety of tooling for the Kubernetes infrastructure that will let us make new discoveries about the behaviour of RabbitMQ.

In this episode, we give you all the tools to set you up to make these discoveries yourself, and show you some of the interesting behaviours that we have discovered.

Closes #19

### CODE REVIEW

**Comment by zhouqiang-cl** [comment]
@gerhard hi, Gerhard, I am Qiang Zhou, a maintainer of Chaos Mesh, we are very glad you using Chaos Mesh to test rabbitmq. Can I invite you to share your experience in some talk such as Chaos Mesh monthly meeting?
Thank you Gerhard.

**Comment by gerhard** [comment]
Hi @zhouqiang-cl & thanks for reaching out 🙂

That's an excellent idea! I will join only if @coro joins as well. Are you up for it @coro? The next meeting is on the 28th of January according to https://github.com/chaos-mesh/chaos-mesh#community-meeting

Thinking longer-term, would you be interested @coro in putting together a canonical set of Chaos Mesh experiments that any RabbitMQ user can run in their environment? The simplest thing may be to add them to https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples, but https://github.com/rabbitmq/chaos-mesh could also work.

Another thing that caught my eye is the [Chaos Mesh Data Source for Grafana](https://grafana.com/grafana/plugins/yeya24-chaosmesh-datasource). That in itself sounds like a great future TGIR episode to me 🤓

I appreciate you kicking off this conversation @zhouqiang-cl, looking forward to where we take it next 😉

**Comment by coro** [comment]
Hello @zhouqiang-cl & to echo what @gerhard said, thank you for reaching out to us! We had a very positive experience working with Chaos Mesh and of course we'd love to come to your community meeting. As for further collaboration I would be interested in helping out. I think there are some limitations that might hinder a canonical set of RabbitMQ chaos events, that I'm happy to raise in the meeting, but overall I like the idea!

**Comment by zhouqiang-cl** [comment]
@gerhard @coro aha, thank you for your quick reply. Did your guys have slack or where I can contact you directly ❤️. Some of our team members will also want to join the meeting

**Comment by gerhard** [comment]
I've sent you an email Zhou, let me know if you didn't get it (remember to check spam first).

**Comment by gerhard** [comment]
[Follow-up with the Chaos Mesh Community from January 28, 2021:](https://twitter.com/chaos_mesh/status/1354114146443423746)

**Pull request merged**
